publish-report:
  needs: test
  runs-on: ubuntu-latest
  if: always()
  steps:
    - name: Download report artifact
      uses: actions/download-artifact@v4
      with:
        name: playwright-report
        path: playwright-report

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: playwright-report
